/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'trmartines' at '4/21/17 1:15 PM' with Gradle 2.9
 *
 * @author trmartines, @date 4/21/17 1:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
